version: '{build}'
image: Visual Studio 2017
configuration: Release
environment:
  sourceFolder: src
  projectName: Client
  solutionName: tdl.sln
  api_key:
    secure: n99aLyTg0+72IVcTor23VDwAXAEsKVPg3kxSod2kI4aVEY7AMtHVy1IJdmX/Zy85
  packageName: TDL.Client
  
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- cmd: git submodule update --init --recursive
  
before_build:
- ps: >-
    nuget restore

    if ($env:APPVEYOR_REPO_TAG -eq "true" -and
        $env:APPVEYOR_REPO_TAG_NAME.StartsWith("v0.")) {
      # Patch NuGet package version into .nuspec file
      $nuspecPath = "$($env:APPVEYOR_BUILD_FOLDER)\$($env:sourceFolder)\$($env:projectName)\$($env:projectName).nuspec"
      $nuspec = [xml](Get-Content $nuspecPath)
      $nuspec.package.metadata.version = "$($env:APPVEYOR_REPO_TAG_NAME.Trim("v"))"
      $nuspec.Save($nuspecPath)
    }

build:
  project: $(solutionName)
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

before_test:
- ps: $TestSetup = Start-Process test-setup.cmd -Wait

after_test:
- ps: Stop-Process $TestSetup -Id $TestSetup.Id

deploy:
- provider: NuGet
  api_key: $(api_key)
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true
    APPVEYOR_REPO_TAG_NAME: /v0.*/
